In [4]:
import torch
import torchvision
import numpy as np
import math
from torch.utils.data import Dataset, DataLoader
import pandas as pd

In [35]:
class WineDataset(Dataset):
  def __init__(self):
    xy = np.loadtxt("/content/wine.txt", delimiter=",", dtype=np.float32)
    self.x = torch.from_numpy(xy[:, 1:])
    self.y = torch.from_numpy(xy[:, [0]])
    self.n_samples = xy.shape[0]
  def __getitem__(self, index):
    return self.x[index], self.y[index]
  def __len__(self):
    return self.n_samples

In [36]:
data_set = WineDataset()
first_data = data_set[0]
features, labels = first_data
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [26]:
dataset = WineDataset()
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=2)
dataiter = iter(dataloader)
data = next(dataiter)
features, labels = data
print(features, labels)

tensor([[1.3710e+01, 5.6500e+00, 2.4500e+00, 2.0500e+01, 9.5000e+01, 1.6800e+00,
         6.1000e-01, 5.2000e-01, 1.0600e+00, 7.7000e+00, 6.4000e-01, 1.7400e+00,
         7.4000e+02],
        [1.2850e+01, 1.6000e+00, 2.5200e+00, 1.7800e+01, 9.5000e+01, 2.4800e+00,
         2.3700e+00, 2.6000e-01, 1.4600e+00, 3.9300e+00, 1.0900e+00, 3.6300e+00,
         1.0150e+03],
        [1.2360e+01, 3.8300e+00, 2.3800e+00, 2.1000e+01, 8.8000e+01, 2.3000e+00,
         9.2000e-01, 5.0000e-01, 1.0400e+00, 7.6500e+00, 5.6000e-01, 1.5800e+00,
         5.2000e+02],
        [1.3160e+01, 2.3600e+00, 2.6700e+00, 1.8600e+01, 1.0100e+02, 2.8000e+00,
         3.2400e+00, 3.0000e-01, 2.8100e+00, 5.6800e+00, 1.0300e+00, 3.1700e+00,
         1.1850e+03]]) tensor([[3.],
        [1.],
        [3.],
        [1.]])


In [27]:
dataset = WineDataset()
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=2)

# training
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples / 4) #(batch size)

print(total_samples, n_iterations)

178 45


In [28]:
for epoch in range(num_epochs):
  for i, (inputs, labels) in enumerate(dataloader):
    # forward and backward, and update
    if i % 5 == 0:
      print(f"Epoch: {epoch+1}/{num_epochs}, step: {i+1}/{n_iterations}, inputs: {inputs.shape}")

Epoch: 1/2, step: 1/45, inputs: torch.Size([4, 13])
Epoch: 1/2, step: 6/45, inputs: torch.Size([4, 13])
Epoch: 1/2, step: 11/45, inputs: torch.Size([4, 13])
Epoch: 1/2, step: 16/45, inputs: torch.Size([4, 13])
Epoch: 1/2, step: 21/45, inputs: torch.Size([4, 13])
Epoch: 1/2, step: 26/45, inputs: torch.Size([4, 13])
Epoch: 1/2, step: 31/45, inputs: torch.Size([4, 13])
Epoch: 1/2, step: 36/45, inputs: torch.Size([4, 13])
Epoch: 1/2, step: 41/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 1/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 6/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 11/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 16/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 21/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 26/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 31/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 36/45, inputs: torch.Size([4, 13])
Epoch: 2/2, step: 41/45, inputs: torch.Size([4, 13])


In [37]:
torchvision.datasets.MNIST(root="./data", transform=torchvision.transforms.ToTensor())

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [45]:
class WineDataset(Dataset):
  def __init__(self, transform=None):
    xy = np.loadtxt("/content/wine.txt", delimiter=",", dtype=np.float32)
    self.x = xy[:, 1:]
    self.y = xy[:, [0]]
    self.n_samples = xy.shape[0]
    self.transform = transform
  def __getitem__(self, index):
    sample = self.x[index], self.y[index]
    if self.transform:
      sample = self.transform(sample)
    return sample
  def __len__(self):
    return self.n_samples

class ToTensor:
  def __call__(self, sample):
    inputs, targets = sample
    return torch.from_numpy(inputs), torch.from_numpy(targets)

class MulTransform:
  def __init__(self, factor):
    self.factor = factor
  def __call__(self, sample):
    inputs, targets = sample
    inputs *= self.factor
    return inputs, targets

In [42]:
dataset = WineDataset(transform=ToTensor())
first_data = dataset[0]
features, labels = first_data
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [43]:
compose = torchvision.transforms.Compose([ToTensor(), MulTransform(2)])
dataset = WineDataset(transform=compose)
first_data = dataset[0]
features, labels = first_data
print(features, labels)

tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03]) tensor([1.])
