# Linear Regression

In [28]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [29]:
df = pd.read_excel("/content/HousePrice.xlsx")
df

Area  Price(Dollars)
0  1.00             100
1  2.00             200
2  0.50              50
3  0.25              25

In [30]:
X = df[["Area"]]
y = df["Price(Dollars)"]

In [31]:
model = LinearRegression().fit(X, y)

In [32]:
model.coef_

array([100.])

In [33]:
model.intercept_

np.float64(0.0)

In [34]:
model.predict([[3.00]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([300.])

# Multiple Linear Regression

In [35]:
df = pd.read_excel("/content/SalaryPrediction.xlsx")
df

Experience  TestScore  InterviewScore  Salary
0           5        6.0               7   60000
1           2       10.0              10   65000
2           7        9.0               6   70000
3           3        7.0              10   62000
4          10        NaN               7   72000
5          11        7.0               8   80000

In [36]:
median_test_score = df['TestScore'].median()
df['TestScore'].fillna(median_test_score, inplace=True)
df

/tmp/ipython-input-2829668396.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TestScore'].fillna(median_test_score, inplace=True)


Experience  TestScore  InterviewScore  Salary
0           5        6.0               7   60000
1           2       10.0              10   65000
2           7        9.0               6   70000
3           3        7.0              10   62000
4          10        7.0               7   72000
5          11        7.0               8   80000

In [37]:
X = df[df.columns[:-1]]
y = df[df.columns[-1]]

In [38]:
model = LinearRegression().fit(X, y)

In [39]:
model.coef_

array([2504.3508937 , 2045.97836312, 1674.62370649])

In [40]:
model.intercept_

np.float64(23222.95390404518)

In [41]:
model.predict([[4, 10, 10]]) # candidate with 4years experience, 10 Test score and 10 Interview score will have 70446.37817498 salary

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70446.37817498])

# Joblib

In [42]:
import joblib

In [43]:
joblib.dump(model, "/content/model_linear_regression.pkl")

['/content/model_linear_regression.pkl']

In [44]:
model = joblib.load("/content/model_linear_regression.pkl")

In [45]:
model.predict([[4, 10, 10]]) # candidate with 4years experience, 10 Test score and 10 Interview score will have 70446.37817498 salary

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70446.37817498])